{"author":{"id":"feda26f3edff57c45386a2a6aff3c09285d91aed4dae4979f8fa76a3f1cd2248"},"ops":[{"type":1,"timestamp":1622456239,"metadata":{"github-id":"MDU6SXNzdWU5MDczMzE2OTI=","github-url":"https://github.com/MichaelMure/git-bug/issues/686","origin":"github"},"nonce":"pvZ8/ISBAQWnzqBJBZDTrrHKxUQ=","title":"bridge pull gives: rofi.current/build$ git bug bridge pull panic: runtime error: index out of range [0] with length 0","message":"After an initial pull (that worked) I made an online change (closed bug) and did another bridge pull, this returned the following trace:\n\n```\npanic: runtime error: index out of range [0] with length 0\n\ngoroutine 42 [running]:\ngithub.com/MichaelMure/git-bug/bridge/github.(*iterator).NextTimelineItem(0xc000246140, 0xc000130d00)\n\t/home/michael/dev/git-bug/bridge/github/iterator.go:252 +0x405\ngithub.com/MichaelMure/git-bug/bridge/github.(*githubImporter).ImportAll.func1(0xc0003cc1e0, 0xc000130d80, 0xc00011d140)\n\t/home/michael/dev/git-bug/bridge/github/import.go:75 +0x8a\ncreated by github.com/MichaelMure/git-bug/bridge/github.(*githubImporter).ImportAll\n\t/home/michael/dev/git-bug/bridge/github/import.go:60 +0x1bf\n```\n\nVersion:\n```\n$git bug --version\ngit-bug version v0.7.2\n```\n\nPlease let me know if you need more information.","files":null}]}