{"author":{"id":"30fa3d79cd329aed8fb502f5a92556931752193ec6beaa1a9178689b58f1daba"},"ops":[{"type":3,"timestamp":1616879004,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDgwODgwMjA1NA==","github-url":"https://github.com/MichaelMure/git-bug/issues/606#issuecomment-808802054"},"nonce":"OhaJo6GJzpzLzzE6t9AtMjL73/s=","message":"At the moment I do not know where the error happens exactly (reproducing the error takes a lot of time). Just looking at the error message it should originiate from somewhere below the call to `repo.NewBugRaw()`.\n\nThe cause might be the same as described in the issue which causes the error. There the cause was a `bufio.Scanner` (which has `bufio.MaxScanTokenSize` equal to 65536). The solution which the golang people found was to replace the `bufio.Scanner` by a `bufio.Reader` as described in https://go-review.googlesource.com/c/tools/+/93439/","files":null},{"type":6,"timestamp":1616883741,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlQ29tbWVudEVkaXQ6NDQ2NzU5MDI2"},"nonce":"j8FX1RZoV6zF/lMrEh7tygxOiGQ=","target":"3a97226935f7bc179e88fcde8122310c300f2a50570fa0cfc7edd4730dce693a","message":"At the moment I do not know where the error happens exactly. Just looking at the error message it should originiate from somewhere below the call to `repo.NewBugRaw()`.\n\nThe cause might be the same as described in the issue which causes the error. There the cause was a `bufio.Scanner` (which has `bufio.MaxScanTokenSize` equal to 65536). The solution which the golang people found was to replace the `bufio.Scanner` by a `bufio.Reader` as described in https://go-review.googlesource.com/c/tools/+/93439/","files":null}]}